const courseFinalResult = [
    {
        _id: 1,
        roll: 18102901,
        attendance: 9,
        midOne: 8,
        midTwo: 9,
        assignmentOrPresentation: 9,
        continuous: 35,
        firstExaminer: 35,
        secondExaminer: 40,
        thirdExaminer: "",
        finalMark: 37,
        total: 72,
        LetterGrade: "A-",
        GradePoint: 3.23,
    },
    {
        _id: 2,
        roll: 18102902,
        attendance: 9,
        midOne: 8,
        midTwo: 9,
        assignmentOrPresentation: 9,
        continuous: 35,
        firstExaminer: 35,
        secondExaminer: 40,
        thirdExaminer: "",
        finalMark: 37,
        total: 72,
        LetterGrade: "A-",
        GradePoint: 3.23,
    },
    {
        _id: 3,
        roll: 18102903,
        attendance: 9,
        midOne: 8,
        midTwo: 9,
        assignmentOrPresentation: 9,
        continuous: 35,
        firstExaminer: 35,
        secondExaminer: 40,
        thirdExaminer: "",
        finalMark: 37,
        total: 72,
        LetterGrade: "A-",
        GradePoint: 3.23,
    },
    {
        _id: 4,
        roll: 18102904,
        attendance: 9,
        midOne: 8,
        midTwo: 9,
        assignmentOrPresentation: 9,
        continuous: 35,
        firstExaminer: 35,
        secondExaminer: 40,
        thirdExaminer: "",
        finalMark: 37,
        total: 72,
        LetterGrade: "A-",
        GradePoint: 3.23,
    },
];

export default courseFinalResult;
